#!/bin/sh

# There needs to be a folder at $ANDROID_DATA/dalvik-cache
export ANDROID_DATA=/var/android/
mkdir -p $ANDROID_DATA/dalvik-cache

unset LD_LIBRARY_PATH
exec /system/bin/dalvikvm -Djava.io.tmpdir=/tmp "$@"
